# Default values for status-addon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Set the controller verbosity
controller:
  verbosity: 2

# Set the agent verbosity
agent:
  verbosity: 2