builds:
- id: "ocm-status-addon"
  main: ./cmd/ocm-status-addon
  binary: bin/ocm-status-addon
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
kos:           
  - repository: ghcr.io/kubestellar/ocm-status-addon
    main: ./cmd/ocm-status-addon
    build: ocm-status-addon
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    ldflags:
    - "{{ .Env.LDFLAGS }}"
    platforms:
    - linux/amd64
    - linux/arm64
    env:
    - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing


