kind: Deployment
apiVersion: apps/v1
metadata:
  name: status-controller
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: status-addon
    app.kubernetes.io/part-of: status-addon
    app.kubernetes.io/managed-by: kustomize
    app: status-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-controller
  template:
    metadata:
      labels:
        app: status-controller
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: status-sa
      containers:
      - name: status-controller
        image: controller
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi      
        env:
        - name: STATUS_ADDDON_IMAGE_NAME
          value: STATUS_ADDDON_IMAGE_NAME_PLACEHOLDER
        args:
        - "controller"

