# permissions for end users to edit placementpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: placementpolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: status-addon
    app.kubernetes.io/part-of: status-addon
    app.kubernetes.io/managed-by: kustomize
  name: placementpolicy-editor-role
rules:
- apiGroups:
  - edge.kubestellar.io
  resources:
  - placementpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.kubestellar.io
  resources:
  - placementpolicies/status
  verbs:
  - get

