resources:
# All RBAC will be applied under this service account in
# the deployment namespace.
- service_account.yaml
- role.yaml
- role_binding.yaml

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: addon-
