apiVersion: edge.kubestellar.io/v1alpha1
kind: Placement
metadata:
  name: placement1
spec:
  clusterSelectors:
  - matchLabels: {"location-group":"edge"}
  downsync:
  - labelSelectors:
    - matchLabels: {"app.kubernetes.io/managed-by":"Helm"}
    - matchLabels: {"app.kubernetes.io/instance":"postgres"}

