name: test workstatus creation

on:
  workflow_call:
  # So we can trigger manually if needed
  workflow_dispatch:
  # To confirm any changes to docs build successfully, without deploying them
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test-workstatus-creation:
    name: Test workstatus creation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-go@v5
        with:
          go-version: v1.20
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: Install and setup ko
        uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ko.local

      - name: Install clusteradm
        run: |
          curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh | bash

      - name: Run test
        run: |
          test/e2e/run.sh

      - name: show docker images
        if: always()
        run: docker images

      - name: show kubeconfig contexts
        if: always()
        run: kubectl config get-contexts

      - name: show clustermanagementaddons
        if: always()
        run: kubectl --context kind-hub get clustermanagementaddons

      - name: show managedclusteraddons
        if: always()
        run: kubectl --context kind-hub get managedclusteraddons -A

      - name: show manifestworks in hub
        if: always()
        run: kubectl --context kind-hub get manifestwork -oyaml -A

      - name: show workloads in cluster1
        if: always()
        run: kubectl --context kind-cluster1 get all -A

      - name: show logs of the agent in cluster1
        if: always()
        run: kubectl --context kind-cluster1 -n open-cluster-management-agent-addon logs deployment.apps/status-agent

      - name: show workstatus objects in hub
        if: always()
        run: kubectl --context kind-hub get workstatus -oyaml -A
